version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: compositiondb
      POSTGRES_USER: composition_user
      POSTGRES_PASSWORD: composition_pass
  app:
    build: .
    container_name: composition_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./composition_app:/app
    ports:
      - '3000:3000'
    depends_on:
      - db